### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aeallen** [How-to-Learn-to-Code/rclass#14]
We need to decide on a license for our materials and add the appropriate mark down file. 

I'm proposing the MIT license, but please let me know if you have any suggestions or objections.

**Comment by daynefiler** [comment]
I have no idea what differentiates the licenses. Your call.

**Comment by snystrom** [comment]
MIT's fine. Not like we're developing anything worth patenting anyway. Also depending on the data the package ends up hosting you might want to be careful about what you assign.
