### ISSUE TITLE
Add new plotting lecture

### ISSUE THREAD

**Issue by daynefiler** [How-to-Learn-to-Code/rclass#19]
Tentatively, I am going to introduce that there are two plotting paradigms in R: graphics vs. grid, just to say we are not going to discuss the complicated grid system. I want to talk about plotting regions, coordinate systems, and the graphics drawing functions. I will also highlight the best book — R graphics, Murrell — which is freely available through UNC.

**Comment by daynefiler** [comment]
@siyao-liu Here is the link to the book:

https://search.lib.unc.edu/search?R=UNCb9113002

I would basically like to cover the material in Ch3.

**Comment by daynefiler** [comment]
@siyao-liu I just pushed the first commit on issue-19. Still have A LOT to add, just thought I would show you what I have so far. Not sure how you want to work on this. Hard to use GitHub when simultaneously editing the same file.

**Comment by siyao-liu** [comment]
@daynefiler I just pushed my R color section. Please take a look and let me know if you have any questions/suggestions. Thanks!

**Comment by daynefiler** [comment]
@siyao-liu I ended up making some larger edits. The biggest is I cut the RColorBrewer and colorspace information into a separate vignette. Let me know what you think. Also, two formatting things: keep the google style guide in mind when typing out the R code, and I also typically use two pound signs for comments, but we specify at the top of the document that two indicate R output and one indicates our comments. Comments should be "# your comment". Really nice addition to the lecture!

**Comment by siyao-liu** [comment]
@daynefiler Just read your edits. Looking great. Thanks a lot for the edits. I think it's good to put the RColorBrewer and colorspace information into a separate vignette. We have quite a lot to cover in this plotting lecture, and I think we should focus on base R graphics. The add-on packages should be extra stuff if we have time to cover. 

Thanks for the formatting tips. I will incorporate those rules in my other lecture prep materials. I need to ask you about the google style guide. Let's talk about it in person. Thanks, Dayne!
