### ISSUE TITLE
Break plotting and IO into two vignettes

### ISSUE THREAD

**Issue by daynefiler** [How-to-Learn-to-Code/rclass#6]
Data IO should probably go before plotting in the sequence. Breaking these out will make different approaches to plotting lectures easier.

**Comment by aeallen** [comment]
Just to have it on here, rather than just in an email. The current proposed sequence is: 

        Class 1-2: Introduction
	Class 3: Data structures
	Class 4: Input/Output
	Class 5-6: Plotting
	Class 7: Control statements
	Class 8: Functions
	Class 9: Packages and best practices for reproducible research
	Classes 10-12: Final project

**Comment by daynefiler** [comment]
Looks great. We need to add that to the README

**Comment by daynefiler** [comment]
I have pulled #12 into the issue-06 branch locally, and will merge the two. Will push in a couple hours.

**Comment by daynefiler** [comment]
Can I just say how frustrating it is that the functions for reading Excel files won't take a connection instead of a path?!? Why should users have to DOWNLOAD the file, rather than just passing a url connection?
